arm64: dts: qcom: pmi8950: enable vibrator haptics
msm8953-mainline/linux pull request #216
Opened 2024-11-10 14:40 UTC by M0Rf30

from dmesg:
```
[   14.312943] input: spmi_haptics as /devices/platform/soc@0/200f000.spmi/spmi-0/0-03/200f000.spmi:pmic@3:haptics@c000/input/input4
```
with fftest
```
xiaomi-vince:~$ sudo fftest /dev/input/event4
Force feedback test program.
HOLD FIRMLY YOUR WHEEL OR JOYSTICK TO PREVENT DAMAGES

Device /dev/input/event4 opened
Features:
  * Absolute axes:
    [00 00 00 00 00 00 00 00 ]
  * Relative axes:
    [00 00 ]
  * Force feedback effects types: Periodic, Rumble, Gain,
    Force feedback periodic effects: Square, Triangle, Sine,
    [00 00 00 00 00 00 00 00 00 00 03 07 01 00 00 00 ]
  * Number of simultaneous effects: 16

Setting master gain to 75% ... OK
Uploading effect #0 (Periodic sinusoidal) ... OK (id 0)
Uploading effect #1 (Constant) ... Error: Invalid argument
Uploading effect #2 (Spring) ... Error: Invalid argument
Uploading effect #3 (Damper) ... Error: Invalid argument
Uploading effect #4 (Strong rumble, with heavy motor) ... OK (id 1)
Uploading effect #5 (Weak rumble, with light motor) ... OK (id 2)
```

2024-11-10 20:18 UTC, barni2000 commented on arch/arm64/boot/dts/qcom/pmi8950.dtsi
> +			qcom,play-mode = <HAP_PLAY_BUFFER>;
```suggestion
			qcom,play-mode = <HAP_PLAY_BUFFER>;
			
			status = "disabled";
```

2024-11-10 20:20 UTC, barni2000 commented
The previous attempt had weak rumble is it working fine now?

2024-11-10 21:40 UTC, M0Rf30 commented
> The previous attempt had weak rumble. Is it working fine now?

Same weak rumble, I only synced with 6.11 and cleaned up.

2024-11-10 21:57 UTC, alikates commented
Hi, i had some initial work on adding support for Eccentric Rotating Mass (cheap motor + counterweight) in  https://github.com/msm8953-mainline/linux/commit/3088192deb7f6a4ece90ebd42329f53876512fbb. Idk if you already have this support in place, but otherwide it may be relevant for you 🙂

2024-11-15 20:23 UTC, barni2000 requested changes

2024-11-15 20:23 UTC, barni2000 commented on arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
> +	qcom,wave-shape = <HAP_WAVE_SINE>;
```suggestion
	qcom,wave-shape = <HAP_WAVE_SQUARE>;
```

2024-11-15 20:23 UTC, barni2000 commented on arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
> +	qcom,actuator-type = <HAP_TYPE_LRA>;
```suggestion
	qcom,actuator-type = <HAP_TYPE_ERM>;
```

2024-11-15 20:23 UTC, barni2000 commented on arch/arm64/boot/dts/qcom/pmi8950.dtsi
> +			qcom,play-mode = <HAP_PLAY_BUFFER>;
```suggestion
			qcom,play-mode = <HAP_PLAY_DIRECT>;
```

2024-11-15 20:23 UTC, barni2000 commented on arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
> +	qcom,brake-pattern = [0x3 0x3 0x0 0x0];
```suggestion
	qcom,brake-pattern = <0x3 0x3 0x0 0x0>;
```

2024-11-15 20:37 UTC, barni2000 commented on arch/arm64/boot/dts/qcom/pmi8950.dtsi
> +			qcom,play-mode = <HAP_PLAY_BUFFER>;
It seems driver is not supports direct mode yet.

2024-11-15 20:38 UTC, barni2000 commented on arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
> +	qcom,actuator-type = <HAP_TYPE_LRA>;
ERM is not supported by the driver

2024-11-16 09:19 UTC, barni2000 commented
Driver should be updated a bit to support ERM and DIRECT mode but it will work.

2024-11-18 16:00 UTC, closed without merging