arm64: dts: qcom: msm8953: add device tree for Xiaomi Mi A2 Lite
msm8953-mainline/linux pull request #30
Opened 2022-01-29 23:50 UTC by alikates

I just cleaned up a bit the dts.

2022-02-12 11:11 UTC, vldly requested changes

2022-02-12 11:17 UTC, alikates commented on arch/arm64/boot/dts/qcom/msm8953-xiaomi-daisy.dts
> +		reset-gpios = <&tlmm 89 0>;
Yeah, I forgot to change it, again...

2022-02-12 11:17 UTC, alikates commented on arch/arm64/boot/dts/qcom/msm8953-xiaomi-daisy.dts
> +	sensors: i2c@0 {
Alright

2022-02-12 11:18 UTC, alikates commented on arch/arm64/boot/dts/qcom/msm8953-xiaomi-daisy.dts
> +		compatible = "edt,edt-ft5406", "edt,edt-ft5x06";
Okay, gotta fix all of this

2022-02-12 11:31 UTC, alikates commented
Oops, wait I remember i fixed a couple more things. Let me add them before merging or something

2022-02-12 12:09 UTC, alikates commented
THe only issue is that I'm not sure why the touchscreen probe times out, but then unloading the module and loading it again makes it work

I guess it's okay for now...

2022-06-10 19:57 UTC, alikates commented
We can close this too as the new cleaned-up version is in [msm8953-5.18.3-smbcharger](https://github.com/msm8953-mainline/linux/tree/msm8953-5.18.3-smbcharger)

2022-06-10 19:57 UTC, closed without merging