Add Motorola Moto G6 (motorola-ali)
msm8953-mainline/linux pull request #48
Opened 2022-08-08 21:07 UTC by julianbraha

Still not working:
* Camera
* Audio
* Battery data
* Mobile networks

2022-08-10 14:35 UTC, alikates commented on drivers/gpu/drm/panel/Kconfig
> +	tristate "Tianma TL057FVXP01\" panel"
That escaped quote is intended?

2022-08-10 14:35 UTC, alikates commented on drivers/gpu/drm/panel/Kconfig
> +
Single line maybe?

2022-08-10 16:07 UTC, julianbraha commented on drivers/gpu/drm/panel/Kconfig
> +	tristate "Tianma TL057FVXP01\" panel"
Thanks, didn't catch that. Removed.

2022-08-16 10:21 UTC, alikates commented
Before I merge it, can you fix the conflicts please?

2022-08-17 02:58 UTC, julianbraha commented
> Before I merge it, can you fix the conflicts please?

Done.

2022-08-17 07:27 UTC, M0Rf30 requested changes

2022-08-17 07:27 UTC, M0Rf30 commented on arch/arm64/boot/dts/qcom/sdm450-motorola-ali.dts
> +	qcom,enabled-strings = <0 1 2>;
As far as I know You need only to specify one of these between enabled-strings and num-strings (You should have a warning in the dmesg).

2022-08-17 07:27 UTC, M0Rf30 commented on arch/arm64/boot/dts/qcom/sdm450-motorola-ali.dts
> +	qcom,eternal-pfet;
it's external, not eternal as reported in 

Documentation/devicetree/bindings/leds/backlight/qcom-wled.yaml

and in

drivers/video/backlight/qcom-wled.c

2022-08-17 07:27 UTC, M0Rf30 commented on arch/arm64/boot/dts/qcom/sdm450-motorola-ali.dts
> +		supply-names = "vsp", "vsn";
why you specify vsp and vsn regulators if you don't pass them to the panel?
to pass a regulator to the display generator you need to specify the `-r` option.
something like `-r vsp -r vsn`

2022-08-17 07:51 UTC, M0Rf30 requested changes

2022-08-17 07:51 UTC, M0Rf30 commented on arch/arm64/configs/motorola-ali.config
> +CONFIG_BACKLIGHT_LED=y
Should be CONFIG_BACKLIGHT_QCOM_WLED=y

2022-09-05 21:41 UTC, julianbraha commented
@M0Rf30 Thanks for reviewing! And apologies for my slow response. I've resolved the issues you brought up.

2022-09-06 10:35 UTC, M0Rf30 commented
Good as I've seen you don't use vsp and vsn yet. You can remove them if the panel works. they are not used. As I've told you, you need to pass them at panel generation with `-r` flag

2022-09-06 10:38 UTC, M0Rf30 requested changes
Good. As I've seen, you don't use vsp and vsn yet.
in the panel you should have something like
```
#include <linux/regulator/consumer.h>
struct tianma_tl057fvxp01 {
	struct drm_panel panel;
	struct mipi_dsi_device *dsi;
	struct gpio_desc *reset_gpio;
	struct regulator_bulk_data supplies[2];
	bool prepared;
};

```
```
static int tianma_tl057fvxp01_probe(struct mipi_dsi_device *dsi)
{
	struct device *dev = &dsi->dev;
	struct tianma_tl057fvxp01 *ctx;
	int ret;

	ctx = devm_kzalloc(dev, sizeof(*ctx), GFP_KERNEL);
	if (!ctx)
		return -ENOMEM;

        ctx->supplies[0].supply = "vsn";
	ctx->supplies[1].supply = "vsp";

	ctx->reset_gpio = devm_gpiod_get(dev, "reset", GPIOD_OUT_HIGH);
	if (IS_ERR(ctx->reset_gpio))
		return dev_err_probe(dev, PTR_ERR(ctx->reset_gpio),
				     "Failed to get reset-gpios\n");

	ctx->dsi = dsi;
	mipi_dsi_set_drvdata(dsi, ctx);

	dsi->lanes = 4;
	dsi->format = MIPI_DSI_FMT_RGB888;
	dsi->mode_flags = MIPI_DSI_MODE_VIDEO | MIPI_DSI_MODE_VIDEO_BURST |
			  MIPI_DSI_CLOCK_NON_CONTINUOUS | MIPI_DSI_MODE_LPM;

	drm_panel_init(&ctx->panel, dev, &tianma_tl057fvxp01_panel_funcs,
		       DRM_MODE_CONNECTOR_DSI);

	ret = drm_panel_of_backlight(&ctx->panel);
	if (ret)
		return dev_err_probe(dev, ret, "Failed to get backlight\n");

	drm_panel_add(&ctx->panel);

	ret = mipi_dsi_attach(dsi);
	if (ret < 0) {
		dev_err(dev, "Failed to attach to DSI host: %d\n", ret);
		drm_panel_remove(&ctx->panel);
		return ret;
	}

	return 0;
}
```

They are automatically generated passing  `-r vsp -r vsn` flags at panel generation. 

And you also done something wrong with the commits (perhaps wrong rebase?). Edits of mine should not appear, only yours

2022-10-19 14:52 UTC, julianbraha commented
@M0Rf30 Thanks, that helped. I have re-ported the panel driver (and tested it) with those flags. And also fixed the rebase.

2022-10-21 10:08 UTC, M0Rf30 approved these changes

2022-10-21 10:42 UTC, alikates approved these changes

2022-10-21 10:43 UTC, merged