arm64: dts: qcom: msm8953-xiaomi: enable IrDA transmitter on mido and…
msm8953-mainline/linux pull request #96
Opened 2023-04-30 16:59 UTC by M0Rf30

… markw

2023-04-30 17:15 UTC, vipaoL commented
I can confirm it works on markw, I can turn the ir LED on by executing echo 1 > /sys/class/leds/irled/brightness

2023-04-30 17:57 UTC, M0Rf30 commented
@kiciuk @marc0x1 can you give feedback for mido?

2023-04-30 17:59 UTC, z3ntu commented on arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
> +			linux,default-trigger = "infra-red";
There's no trigger under that name

2023-04-30 18:01 UTC, z3ntu commented
Is there no upstream driver for GPIO IR LED like with `ir-spi-led`? While I haven't looked into the `ir-spi-led` driver I doubt it's getting exposed as a simple LED device, I'm guessing there's some kernel API for IR that then user space uses?

2023-04-30 18:09 UTC, M0Rf30 commented
> Is there no upstream driver for GPIO IR LED like with `ir-spi-led`? While I haven't looked into the `ir-spi-led` driver I doubt it's getting exposed as a simple LED device, I'm guessing there's some kernel API for IR that then user space uses?

Yeah maybe I found gpio-ir-tx. I will give it a try

2023-06-01 17:39 UTC, marc0x1 commented
> @Kiciuk @marc0x1 can you give feedback for mido?
Can you provide, if you have it, the compiled version?

2023-07-02 01:10 UTC, barni2000 commented
I have tested on mido the driver is initialized and it creates /dev/lirc0. I try to use with ir-ctl but unfortunately it doesn't work for me.

2023-07-02 12:08 UTC, barni2000 commented
As i see in the downstream source for mido we should use [pwm-ir-tx](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/leds/irled/pwm-ir-tx.yaml?h=v6.4)

Downstream node:
```
pwm_ir {
	compatible = "pwm-ir";
	pwms = <&pmi8950_pwm 0 0>;
	reg-id = "vdd";
	vdd-supply = <&pm8953_l8>;
};
```

2023-07-02 12:11 UTC, M0Rf30 commented
> As i see in the downstream source for mido we should use [pwm-ir-tx](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/leds/irled/pwm-ir-tx.yaml?h=v6.4)
> 
> Downstream node:
> 
> ```
> pwm_ir {
> 	compatible = "pwm-ir";
> 	pwms = <&pmi8950_pwm 0 0>;
> 	reg-id = "vdd";
> 	vdd-supply = <&pm8953_l8>;
> };
> ```

Thanks for the suggestion. I will test today I think

2023-07-03 16:48 UTC, M0Rf30 commented
> compatible = "pwm-ir";

I enabled the pwm generator for pmi8950 and use of pwm-ir-tx,
I can't test it. let me know

2023-07-03 18:12 UTC, barni2000 commented
@M0Rf30 I am going to check on mido, but i see you changed markw but it uses gpio-ir. The two device has different irled solution.

2023-07-03 18:51 UTC, barni2000 commented
> @barni2000 @vipaoL I enabled the pwm generator for pmi8950 and use of pwm-ir-tx, I can't test it. let me know Judging from various dts the pwm node should live in pmic@3 node, has a reg = 0xb000 and one channel (`chanid=0`). So basically a msm8916-pwm with different .base. Some devices (sdm450) also enable a pm8950_pwm (not pmi), on pmic@1 and reg 0xbc00 (seems equivalent to msm8916-pwm)
> 
> Don't forget to enable required kernel modules
> 
> https://github.com/search?q=repo%3ASonicBSV%2Fandroid_kernel_xiaomi_markw-4.9%20pmi8950_pwm&type=code

I have test but unfortunately it is not reacts for anything. The drivers are initialized i have /dev/lirc0 but the led is not working for me.

2024-01-27 01:07 UTC, barni2000 commented
I have added pmi8950_gpio pinctrl for mido and it is working now.

2024-01-27 01:08 UTC, barni2000 requested changes

2024-01-27 01:08 UTC, barni2000 commented on drivers/leds/rgb/leds-qcom-lpg.c
> +static const struct lpg_data pm8950_pwm_data = {
it should be called as pmi8950 instead of pm8950.

2024-01-27 01:08 UTC, barni2000 commented on drivers/leds/rgb/leds-qcom-lpg.c
> +	{ .compatible = "qcom,pm8950-pwm", .data = &pm8950_pwm_data },
pmi8950

2024-01-27 11:05 UTC, closed without merging

2024-01-27 11:16 UTC, barni2000 commented
@M0Rf30 will you send it to upstream?

2024-01-27 11:23 UTC, M0Rf30 commented
I think to upstream this and posting a link here

2024-04-15 20:05 UTC, M0Rf30 commented
In linux-next
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20240415&id=2573c25e2c482b53b6e1142ff3cd28f6de13e659
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20240415&id=fc3b23faa14371182ca8a3806854f0db827cb91f